"""jpkara 输出 ASS 的头部定义（与 aegisub-tools 样式兼容）。"""

JPKARA_ASS_HEADER = """\
[Script Info]
; Script generated by jpkara
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default-furigana,Source Han Sans Heavy,60,&H00FFFFFF,&H00FF5E00,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,11,11,11,1
Style: Default,Source Han Sans Heavy,120,&H00FFFFFF,&H00FF5E00,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,11,11,11,1
Style: K1-furigana,Source Han Sans Heavy,50,&H00FFFFFF,&H00FF0000,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2.5,0,1,120,30,260,1
Style: K1,Source Han Sans Heavy,120,&H00FFFFFF,&H00FF0000,&H00000000,&H80000000,0,0,0,0,100,100,5,0,1,5,0,1,120,30,240,1
Style: K2-furigana,Source Han Sans Heavy,50,&H00FFFFFF,&H00FF0000,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2.5,0,3,30,120,70,1
Style: K2,Source Han Sans Heavy,120,&H00FFFFFF,&H00FF0000,&H00000000,&H80000000,0,0,0,0,100,100,5,0,1,5,0,3,30,120,70,1
Style: Intro-furigana,Source Han Sans Bold,35,&H00FFFFFF,&H00FF0000,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2.5,0,1,120,40,480,1
Style: Intro,Source Han Sans Bold,70,&H00FFFFFF,&H00FF0000,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,5,0,1,120,40,400,1
Style: Title,Source Han Serif JP Heavy,50,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,7,40,120,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
